"""add_staff_attendance_settings_fields

Revision ID: 38c17551429e
Revises: 52f162032357
Create Date: 2025-08-29 23:20:33.265823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c17551429e'
down_revision = '52f162032357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_settings', sa.Column('staff_clock_in_start_time', sa.String(length=10), nullable=True))
    op.add_column('school_settings', sa.Column('staff_clock_in_end_time', sa.String(length=10), nullable=True))
    op.add_column('school_settings', sa.Column('staff_clock_out_start_time', sa.String(length=10), nullable=True))
    op.add_column('school_settings', sa.Column('staff_clock_out_end_time', sa.String(length=10), nullable=True))
    op.add_column('school_settings', sa.Column('staff_late_threshold_minutes', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_overtime_threshold_hours', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_auto_mark_absent_hours', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_attendance_methods', sa.JSON(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_leave_approval_workflow', sa.String(length=50), nullable=True))
    op.add_column('school_settings', sa.Column('staff_leave_auto_approve_hours', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_leave_types', sa.JSON(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_work_days', sa.JSON(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_holiday_calendar_enabled', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_attendance_reports_enabled', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('staff_attendance_notifications_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_settings', 'staff_attendance_notifications_enabled')
    op.drop_column('school_settings', 'staff_attendance_reports_enabled')
    op.drop_column('school_settings', 'staff_holiday_calendar_enabled')
    op.drop_column('school_settings', 'staff_work_days')
    op.drop_column('school_settings', 'staff_leave_types')
    op.drop_column('school_settings', 'staff_leave_auto_approve_hours')
    op.drop_column('school_settings', 'staff_leave_approval_workflow')
    op.drop_column('school_settings', 'staff_attendance_methods')
    op.drop_column('school_settings', 'staff_auto_mark_absent_hours')
    op.drop_column('school_settings', 'staff_overtime_threshold_hours')
    op.drop_column('school_settings', 'staff_late_threshold_minutes')
    op.drop_column('school_settings', 'staff_clock_out_end_time')
    op.drop_column('school_settings', 'staff_clock_out_start_time')
    op.drop_column('school_settings', 'staff_clock_in_end_time')
    op.drop_column('school_settings', 'staff_clock_in_start_time')
    # ### end Alembic commands ### 