"""add_staff_attendance_models

Revision ID: 52f162032357
Revises: c7ee67476292
Create Date: 2025-08-29 22:39:28.542361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f162032357'
down_revision = 'c7ee67476292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_attendance',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'ON_LEAVE', 'SICK_LEAVE', 'PERSONAL_LEAVE', 'HOLIDAY', name='staffattendancestatus'), nullable=False),
    sa.Column('method', sa.Enum('MANUAL', 'BIOMETRIC', 'RFID', 'QR_CODE', 'MOBILE_APP', 'WEB_PORTAL', name='staffattendancemethod'), nullable=False),
    sa.Column('expected_check_in', sa.Time(), nullable=True),
    sa.Column('expected_check_out', sa.Time(), nullable=True),
    sa.Column('actual_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('minutes_late', sa.Integer(), nullable=True),
    sa.Column('minutes_early_departure', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('marked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=True),
    sa.Column('overtime_hours', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marked_by_user_id'], ['users.id'], name=op.f('fk_staff_attendance_marked_by_user_id_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_staff_attendance_school_id_schools')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_attendance_staff_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_attendance'))
    )
    op.create_index(op.f('ix_staff_attendance_attendance_date'), 'staff_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_id'), 'staff_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_school_id'), 'staff_attendance', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_staff_id'), 'staff_attendance', ['staff_id'], unique=False)
    op.create_table('staff_attendance_summary',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('late_days', sa.Integer(), nullable=True),
    sa.Column('half_days', sa.Integer(), nullable=True),
    sa.Column('leave_days', sa.Integer(), nullable=True),
    sa.Column('total_hours_worked', sa.Integer(), nullable=True),
    sa.Column('total_overtime_hours', sa.Integer(), nullable=True),
    sa.Column('average_check_in_time', sa.Time(), nullable=True),
    sa.Column('average_check_out_time', sa.Time(), nullable=True),
    sa.Column('attendance_percentage', sa.Integer(), nullable=True),
    sa.Column('punctuality_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_staff_attendance_summary_school_id_schools')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_attendance_summary_staff_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_attendance_summary'))
    )
    op.create_index(op.f('ix_staff_attendance_summary_id'), 'staff_attendance_summary', ['id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_summary_month'), 'staff_attendance_summary', ['month'], unique=False)
    op.create_index(op.f('ix_staff_attendance_summary_school_id'), 'staff_attendance_summary', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_summary_staff_id'), 'staff_attendance_summary', ['staff_id'], unique=False)
    op.create_table('staff_leave',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('SICK_LEAVE', 'PERSONAL_LEAVE', 'ANNUAL_LEAVE', 'MATERNITY_LEAVE', 'PATERNITY_LEAVE', 'EMERGENCY_LEAVE', 'OTHER', name='leavetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_staff_leave_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_staff_leave_school_id_schools')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_leave_staff_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_leave'))
    )
    op.create_index(op.f('ix_staff_leave_end_date'), 'staff_leave', ['end_date'], unique=False)
    op.create_index(op.f('ix_staff_leave_id'), 'staff_leave', ['id'], unique=False)
    op.create_index(op.f('ix_staff_leave_school_id'), 'staff_leave', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_leave_staff_id'), 'staff_leave', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_leave_start_date'), 'staff_leave', ['start_date'], unique=False)
    op.create_table('staff_schedule',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('is_working_day', sa.Boolean(), nullable=True),
    sa.Column('is_flexible', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_staff_schedule_school_id_schools')),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_schedule_staff_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_schedule'))
    )
    op.create_index(op.f('ix_staff_schedule_day_of_week'), 'staff_schedule', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_staff_schedule_id'), 'staff_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_staff_schedule_school_id'), 'staff_schedule', ['school_id'], unique=False)
    op.create_index(op.f('ix_staff_schedule_staff_id'), 'staff_schedule', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_schedule_staff_id'), table_name='staff_schedule')
    op.drop_index(op.f('ix_staff_schedule_school_id'), table_name='staff_schedule')
    op.drop_index(op.f('ix_staff_schedule_id'), table_name='staff_schedule')
    op.drop_index(op.f('ix_staff_schedule_day_of_week'), table_name='staff_schedule')
    op.drop_table('staff_schedule')
    op.drop_index(op.f('ix_staff_leave_start_date'), table_name='staff_leave')
    op.drop_index(op.f('ix_staff_leave_staff_id'), table_name='staff_leave')
    op.drop_index(op.f('ix_staff_leave_school_id'), table_name='staff_leave')
    op.drop_index(op.f('ix_staff_leave_id'), table_name='staff_leave')
    op.drop_index(op.f('ix_staff_leave_end_date'), table_name='staff_leave')
    op.drop_table('staff_leave')
    op.drop_index(op.f('ix_staff_attendance_summary_staff_id'), table_name='staff_attendance_summary')
    op.drop_index(op.f('ix_staff_attendance_summary_school_id'), table_name='staff_attendance_summary')
    op.drop_index(op.f('ix_staff_attendance_summary_month'), table_name='staff_attendance_summary')
    op.drop_index(op.f('ix_staff_attendance_summary_id'), table_name='staff_attendance_summary')
    op.drop_table('staff_attendance_summary')
    op.drop_index(op.f('ix_staff_attendance_staff_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_school_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    # ### end Alembic commands ### 