"""add_visitor_management_models

Revision ID: 86cd25054bbd
Revises: 38c17551429e
Create Date: 2025-08-29 23:54:32.620632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cd25054bbd'
down_revision = '38c17551429e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school_settings', sa.Column('visitor_management_enabled', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_approval_workflow', sa.String(length=50), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_auto_approve_parent_visits', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_require_id_verification', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_notify_host_on_arrival', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_notify_parent_on_visitor', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_notify_security_on_overstay', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_print_badges', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_badge_expiry_hours', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_enable_blacklist', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_enable_emergency_evacuation', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_integrate_with_gate_pass', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_enable_qr_codes', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_allow_pre_registration', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_pre_registration_hours_ahead', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_auto_approve_pre_registered', sa.Boolean(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_visiting_hours_start', sa.String(length=10), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_visiting_hours_end', sa.String(length=10), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_max_duration_hours', sa.Integer(), nullable=True))
    op.add_column('school_settings', sa.Column('visitor_auto_checkout_after_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school_settings', 'visitor_auto_checkout_after_hours')
    op.drop_column('school_settings', 'visitor_max_duration_hours')
    op.drop_column('school_settings', 'visitor_visiting_hours_end')
    op.drop_column('school_settings', 'visitor_visiting_hours_start')
    op.drop_column('school_settings', 'visitor_auto_approve_pre_registered')
    op.drop_column('school_settings', 'visitor_pre_registration_hours_ahead')
    op.drop_column('school_settings', 'visitor_allow_pre_registration')
    op.drop_column('school_settings', 'visitor_enable_qr_codes')
    op.drop_column('school_settings', 'visitor_integrate_with_gate_pass')
    op.drop_column('school_settings', 'visitor_enable_emergency_evacuation')
    op.drop_column('school_settings', 'visitor_enable_blacklist')
    op.drop_column('school_settings', 'visitor_badge_expiry_hours')
    op.drop_column('school_settings', 'visitor_print_badges')
    op.drop_column('school_settings', 'visitor_notify_security_on_overstay')
    op.drop_column('school_settings', 'visitor_notify_parent_on_visitor')
    op.drop_column('school_settings', 'visitor_notify_host_on_arrival')
    op.drop_column('school_settings', 'visitor_require_id_verification')
    op.drop_column('school_settings', 'visitor_auto_approve_parent_visits')
    op.drop_column('school_settings', 'visitor_approval_workflow')
    op.drop_column('school_settings', 'visitor_management_enabled')
    # ### end Alembic commands ### 