"""fix_super_admin_models

Revision ID: c7ee67476292
Revises: 04425aadf52f
Create Date: 2025-08-25 00:29:31.593674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ee67476292'
down_revision = '04425aadf52f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 