"""add_profile_image_fields

Revision ID: fe213c3e6f48
Revises: 044b78cfb9bc
Create Date: 2025-08-24 02:19:51.482339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe213c3e6f48'
down_revision = '044b78cfb9bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('profile_image', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('students', 'profile_image')
    # ### end Alembic commands ### 